name: /projects/NS9560K/diagnostics/cmordev_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argcomplete=3.6.2=pyhd8ed1ab_0
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.9.1=h48c9088_3
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h82d11aa_3
  - aws-c-http=0.10.4=h94feff3_3
  - aws-c-io=0.22.0=h57f3b0d_1
  - aws-c-mqtt=0.13.3=h2b1cf8c_6
  - aws-c-s3=0.8.6=h4e5ac4b_5
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.4=h60c762c_0
  - aws-sdk-cpp=1.11.606=h32384e2_4
  - azure-core-cpp=1.16.0=h3a458e0_1
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=h4bb41a7_3
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.8.0=pyhd8ed1ab_0
  - bottleneck=1.6.0=np2py313hc18bace_3
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py313h7033f15_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cartopy=0.25.0=py313h08cd8bf_1
  - cf_xarray=0.10.9=pyhd8ed1ab_0
  - cffi=2.0.0=py313hf01b4d8_0
  - cftime=1.6.4=py313h29aa505_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - cmip7-repack=0.5.1=pyha804496_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py313h7037e92_3
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.0.1=py313h536fd9c_0
  - distributed=2025.9.1=pyhcf101f3_0
  - eofs=2.0.0=pyhff2d567_0
  - esmf=8.9.0=nompi_h8d4c64c_3
  - esmpy=8.9.0=pyhc455866_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - fonttools=4.60.1=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - geocat-comp=2025.10.01=pyhd8ed1ab_0
  - geos=3.14.0=h480dda7_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=21.0.0=h56a6dad_8_cpu
  - libarrow-acero=21.0.0=h635bf11_8_cpu
  - libarrow-compute=21.0.0=h8c2c5c3_8_cpu
  - libarrow-dataset=21.0.0=h635bf11_8_cpu
  - libarrow-substrait=21.0.0=h3f74fd7_8_cpu
  - libblas=3.9.0=39_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=39_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=39_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=21.0.0=h790f06f_8_cpu
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.08.12=h7b12aa8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h8261f1e_0
  - libudunits2=2.2.28=h40f5838_3
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=h5347b49_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.15.0=h26afc86_1
  - libxml2-16=2.15.0=ha9997c6_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.45.1=py313hdd307be_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py313hdd09ace_1
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib-base=3.10.6=py313h683a580_1
  - metpy=1.7.1=pyhd8ed1ab_0
  - msgpack-python=1.1.2=py313h7037e92_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.7.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - netcdf-fortran=4.6.2=nompi_h90de81b_102
  - netcdf4=1.7.2=nompi_py313hfae5b86_104
  - nlohmann_json=3.12.0=h54a6638_1
  - numba=0.62.1=py313h7afe1cf_1
  - numpy=2.3.3=py313hf6604e3_0
  - openblas=0.3.30=pthreads_h6ec200e_4
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h08cd8bf_2
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.3.0=py313ha492abd_3
  - pint=0.25.2=pyhcf101f3_0
  - pip=25.2=pyh145f28c_0
  - pipx=1.7.1=pyhd8ed1ab_1
  - pooch=1.8.2=pyhd8ed1ab_3
  - proj=9.7.0=hb72c0af_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - properscoring=0.1=pyhd8ed1ab_1
  - psutil=7.1.0=py313h07c4f96_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=21.0.0=py313h78bf25f_1
  - pyarrow-core=21.0.0=py313he109ebe_1_cpu
  - pycparser=2.22=pyh29332c3_1
  - pyfive=1.0.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py313h77f6078_2
  - pyshp=3.0.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.7=h2b335a9_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h3dea7bd_0
  - qhull=2020.2=h434a139_5
  - re2=2025.08.12=h5301d42_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhcf101f3_1
  - s2n=1.5.26=h5ac9029_0
  - scikit-learn=1.7.2=py313h06d4379_0
  - scipy=1.16.2=py313h11c21cd_0
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py313hfc84eb1_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sparse=0.17.0=pyhcf101f3_0
  - sqlite=3.50.4=hbc0de68_0
  - statsmodels=0.14.5=py313h29aa505_1
  - tblib=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.2=py313h07c4f96_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h8577fbf_1
  - udunits2=2.2.28=h40f5838_3
  - urllib3=2.5.0=pyhd8ed1ab_0
  - userpath=1.9.2=pyhd8ed1ab_0
  - xesmf=0.8.7=pyhd8ed1ab_0
  - xhistogram=0.3.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xskillscore=0.0.27=pyhd8ed1ab_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py313h54dd161_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - alabaster==0.7.16
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - certifi==2025.11.12
      - cfgv==3.4.0
      - cmip7-data-request-api==1.4
      - cmor==3.14.0
      - dask==2024.12.1
      - distlib==0.4.0
      - docutils==0.19
      - et-xmlfile==2.0.0
      - filelock==3.19.1
      - fsspec==2023.12.2
      - gents==0.9.3
      - gitdb==4.0.12
      - gitpython==3.1.45
      - identify==2.6.15
      - imagesize==1.4.1
      - iniconfig==2.1.0
      - mdurl==0.1.2
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - nodeenv==1.9.1
      - openpyxl==3.1.5
      - pathspec==0.12.1
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - pydeps==3.0.2
      - pyfakefs==5.10.2
      - pygments==2.19.2
      - pytest==8.4.2
      - ruff==0.6.9
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soupsieve==2.8
      - sphinx==5.3.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stdlib-list==0.12.0
      - virtualenv==20.35.4
      - wheel==0.42.0
      - wrapt==2.0.1
      - xarray==2024.11.0
prefix: /projects/NS9560K/diagnostics/cmordev_env
